CREATE TABLE [dbo].[BB_giftdetail]
(
[Gf_Date] [datetime] NULL,
[Gf_Amount] [money] NULL,
[Gf_Acknowledge] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Batch_Number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_EFT] [bit] NOT NULL,
[Gf_Hon_Mem_name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Installment_schedule] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Letter_code] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Pay_method] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Planned_gift_status] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Balance] [money] NULL,
[Gf_SCMGFlag] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Solicitor_names] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Write-off_note] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Pay_method2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Acknowledge_date] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Appeal] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Campaign] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Fund] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Gift_subtype] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Package] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_CnBio_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_CnAls_1_01_Alias] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Cmps_1_01_Campaign_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Fnds_1_01_Fund_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Apls_1_01_Appeal_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Pks_1_01_Package_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_AttrCat_1_01_Description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Sol_1_01_Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_Sol_1_02_Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_SfCrdt_1_01_Constit_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_SfCrdt_1_01_Constit_Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gf_SfCrdt_1_01_Amount] [money] NULL,
[Gf_WO_1_01_Date] [datetime] NULL,
[Gf_WO_1_01_Amount] [money] NULL,
[Gf_Adj_1_01_Amount] [money] NULL,
[Gf_Adj_1_01_Date] [datetime] NULL,
[Gf_Adj_1_01_System_Record_ID] [int] NULL
)
GO
