IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSBCLOUD\SQL Deployers')
CREATE LOGIN [SSBCLOUD\SQL Deployers] FROM WINDOWS
GO
CREATE USER [SSBCLOUD\SQL Deployers] FOR LOGIN [SSBCLOUD\SQL Deployers]
GO
